name: Send advisory

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      advisory_url:
        type: string

jobs:
  send-modified-files:
    name: Send advisory files added today, or send advisory from input url
    runs-on: ubuntu-latest
    steps:
      - name: Send advisory
        uses: actions/checkout@v3
        run: ./.github/scripts/send-advisory.py "${{ inputs.advisory_url }}"
