name: Send advisory

on:
  push:
    branches: ['main']


env: # sendgrid api token
  sendgrid_api: ${{ secrets.SENDGRID_API }}

permissions:
  contents: read

jobs:
  send-modified-files:
    name: Send advisory files created in last hour
    runs-on: ubuntu-latest
    environment:
      name: communication
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout docs
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 2
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: install requirements
        run: pip install -r requirements.txt
      - name: Send advisories
        run: ./.github/scripts/send-advisory.py --auto
