# Simple workflow for testing mkdocs build
name: Test building TLP:CLEAR content

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: install mkdocs
        run: pip install -r requirements.txt
      - name: run mdformat
        run: mdformat .
      - name: build site
        run:  python -m mkdocs build --strict
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git diff --quiet && git diff --staged --quiet || (git add . && git commit -m 'Format markdown files')
          git push
